spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/quizProject
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /resources/**

  devtools:
    livereload:
      enabled: true

server:
  port: 8080

mybatis:
  config:
  type-aliases-package: com.game.project.**
  mapper-locations: mybatis/mapper/**/*.xml
